language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_install:
  - if [[ -n $GITHUB_TOKEN ]]; then composer config -g github-oauth.github.com $GITHUB_TOKEN; fi
  - composer self-update

install: composer install --no-interaction
  
script: php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

cache:
  directories: vendor

after_success: if [[ $TRAVIS_PHP_VERSION = "5.3" ]]; then bash <(curl -s https://codecov.io/bash); fi;
