language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    
before_cache:
  - rm -f vendor/autoload.php
  - rm -rf vendor/composer/*.php

before_script:
  - if [[ -n $GITHUB_TOKEN ]]; then composer config -g github-oauth.github.com $GITHUB_TOKEN; fi
  - composer install --no-interaction
  
script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  
after_script:
  - php vendor/bin/coveralls
